import Head from 'next/head';

export default function Header() {
    return (
      <>
        <Head>
          <title>Trabalho TEC</title>
          <link rel="icon" type="image/x-icon" href="https://miro.medium.com/v2/resize:fit:1100/format:webp/1*ibzRFIPL3wL2-LuRUdOb2g.jpeg"></link>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="initial-scale=1, width=device-width" />
        </Head>
      </>
    )
}