import Head from 'next/head'
import { Avatar, Link, Toolbar, Container, Box } from '@mui/material';
import style from "../styles/MainPage.module.css"

function Navbar(){
  return(
    <>
    <Toolbar sx={{ flexWrap: 'wrap', bgcolor: '#3a3838' }}>
        <Box sx={{ flexGrow: 1 }}>
          <Avatar alt="Remy Sharp" src="https://miro.medium.com/v2/resize:fit:1100/format:webp/1*ibzRFIPL3wL2-LuRUdOb2g.jpeg"/>
        </Box>
        <nav>
          <Link
            variant="button"
            color="#FFCD01"
            href="/primeiraPagina"
            sx={{ my: 1, mx: 1.5, textDecoration: 'none' }}
          >
            Figura-fundo
          </Link>
          <Link
            variant="button"
            color="#FFCD01"
            href="#"
            sx={{ my: 1, mx: 1.5, textDecoration: 'none' }}
          >
            Pragnanz
          </Link>
          <Link
            variant="button"
            color="#FFCD01"
            href="#"
            sx={{ my: 1, mx: 1.5, textDecoration: 'none'}}
          >
            Similaridade
          </Link>
        </nav> 
      </Toolbar>
    </>

  )
}

function MainPage(){

  return(

    <>
      <section>
          <Box height="calc(100vh - 64px)" display="flex" flexDirection="column" sx={{ bgcolor: '#252525', color: 'whitesmoke', justifyContent: 'center', alignItems: 'center' }}>
            <h1 className={style.h1}>Teoria das Formas </h1>
            <h3 className={style.h3}>As Leis da Gestalt</h3>
          </Box>
      </section>
    </>
    
  )

}

export default function Home() {
  return (
    <>
      <Head>
        <title>Trabalho TEC</title>
        <link rel="icon" type="image/x-icon" href="https://miro.medium.com/v2/resize:fit:1100/format:webp/1*ibzRFIPL3wL2-LuRUdOb2g.jpeg"></link>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="initial-scale=1, width=device-width" />
      </Head>
      <Navbar/>
      <main>
        <MainPage/>
      </main>
    </>
  )
}
